### ISSUE TITLE
Step 4: 👍 Choose a project & create a Vision Statement

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v51-tier2-team-23#6]
**__Task Description__**
Tier 1 & Tier 2 teams will be assigned a project. Tier 3 teams have the choice of creating a project from specifications provided by Chingu or choosing your own project. Check your team channel for more information on which project you are asked to complete.

For Tier 3 teams who choose to create their own project:
- [ ] Watch the [How to Select a Voyage Project](https://youtu.be/5Xv0C5VAKZc) video
[![video link](https://img.youtube.com/vi/Hdn1V645Rwk/0.jpg)](https://youtu.be/5Xv0C5VAKZc)
- [x] Collect ideas from the team
- [x] Brainstorm with your team
- [x] Vote to select one idea
- [x] Decide on the technical stack you’ll use to build your project

**__Technical Considerations__**
N/a

**__Additional Considerations__**
Use the [Project Vision and Feature Planning template](https://docs.google.com/document/d/1hod0AJXVe1T9HDqSwLr6VGXBz0HJ-HG4aM8JKoeBB00/edit?usp=sharing) to gather & vote on everyone's idea

**__Resources__**
[Choose a Project & create a Vision Statement (Chingu Handbook)](https://github.com/chingu-voyages/Handbook/blob/main/docs/guides/voyage/voyage.md#3-choose-a-project--create-a-vision-statement)

**Member of Epic:** #16

**Comment by evaristoc** [comment]
All these points were completed between 2-9 and 16-9, with a final presentation during our last meeting (16-09-2024).

**Comment by evaristoc** [comment]
Below summary of your conclusions:

> The project vision suggested by the proposed US was simplified ( it was also a vision by @hmcf that was shared by @Tesfaye and explained during the meeting ).
> The app should be understood as one-time quick use
> Therefore, there is no need for a member as there is no registration
> Also, the user who creates a group is the only real user - there are no need of registered participants because they are manually inserted by the person who creates the group; therefore "group admin" is no longer a required role.
> The only issue I personally found was that it is likely that the Group list is also not required, as there is no association of the created groups to a "unregistered" person. However, we are open to interpret this challenge as we want, so it will stay as task for Sprint 1 for now.
> 
> The calculator should be modified
> This is probably the core of the project
> @Em M and I suggested a modified model to the one conceived by @Tesfaye that make more sense as "calculator" on our view, with additional data available and the possibility to start the calculation by modifying other cells instead of only the weight. We will try to keep this simple... but not too simple 🙂 .
> 
> The wireframe to be used for the project is the one by @Tesfaye 
> If @Tesfaye can kindly add unique names to the frames in the wireframe, we could add those as references for the user stories
> It appears that there were one or two frames missing for which there is a user story / Chingu requirement?
> 
> The procedure for the acceptance test was explained
> 
> The sprint is open, @Em M and I will be modifying the acceptance criteria along the way
> It is time to pick some tasks 🙂
> https://tier2team23.atlassian.net/jira/software/projects/SCRUM/boards/1 
>
