### ISSUE TITLE
Step 8: ⚙️ Set Up a Team Workflow

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v51-tier2-team-23#9]
**__Task Description__**
- [x] Decide on the coding standards the team must follow.
- [x] Define the characteristics of your repo including the number of branches, branch names, & the workflow everyone must follow.
- [x] Agree on the format of commit messages, how Pull Requests will be reviewed, and GitHub branch protection rules.
- [x] Decide on where you’ll deploy your app and the branch to be considered as ‘production’ you’ll be deploying from.
- [x] Decide on what meetings you’ll need each week and to save time, schedule them as recurring meetings. You might want to look ahead to [Reaching your MVP](https://github.com/chingu-voyages/Handbook/blob/main/docs/guides/voyage/voyage.md#sprint-3-5---reaching-your-mvp) to learn more about the types of meetings you’ll need.

**__Technical Considerations__**
N/a

**__Additional Considerations__**
[Setup Your Team Workflow (Chingu Handbook)](https://www.notion.so/chingucohorts/Voyages-1e528dcbf1d241c9a93b4627f6f1c809#04c66351937d48b589d835164a4ca0d5](https://github.com/chingu-voyages/Handbook/blob/main/docs/guides/voyage/voyage.md#7-setup-your-team-workflow))
[Javascript Style Guides](https://codeburst.io/5-javascript-style-guides-including-airbnb-github-google-88cbc6b2b7aa)
[Defining a Git Workflow (Chingu Handbook)](https://github.com/chingu-voyages/Handbook/blob/main/docs/resources/techresources/gitgithub.md#the-workflow)
[Git Branches (Chingu Handbook)](https://github.com/chingu-voyages/Handbook/blob/main/docs/resources/techresources/gitgithub.md#git-branches)
[Git Pull Requests (Chingu Handbook)](https://github.com/chingu-voyages/Handbook/blob/main/docs/resources/techresources/gitgithub.md#git-pull-requests)

**Member of Epic:** #16

**Comment by evaristoc** [comment]
This was discussed and aggree on our chat during the first week of our project, using the chat. A summary of our last conclusions as on the chat:

> Please read the project specs (https://github.com/chingu-voyages/voyage-project-tier2-expensesplitter) and check the draft of a flow diagram prepared by @Tesfaye ⁠tier2-team-23⁠Welcome to your team channel
> We will use React under CRA; routes will be used so they should be also installed; I think we might need Redux at some point, or handmade pub-subs, but this can wait until next week
> CSS we had a first agreement to keep it vanilla
> It is suggested to keep the repository with just 2 branches: production and development. An staging branch can also be added if we see it useful. Rules for preparing your work will be:
> implement unit testing, even if a simple test file with just one or two positive tests (get used to showing best practices...)
> push to development when you think you are ready
> if ok, we push to staging when all features are ready
> so far the functional / acceptance testings are planned after the whole push of all features are completed
> production will be used only when MVP is completed
> Keep in mind that this is not a backend project, all data will be stored in the front end, and therefore data sharing between different clients should not be expected, neither long term data persistence
> We will use Jira for ticketing
